name: E2E (iOS)

on:
  push:
    branches:
      - '02-26-DetoxTests'

jobs:
  build:
    name: E2E (iOS)
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install yarn Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Generate ios folder
        run: yarn expo prebuild --platform ios

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox Build
        run: yarn run iosReleaseBuild

      - name: Run Detox Test(s)
        run: yarn run iosReleaseE2E
