name: E2E (Android)

on:
  push:
    branches:
      - '02-26-DetoxTests'

jobs:
  build:
    name: E2E (Android)
    runs-on: macOS-latest
    #env:
      #DETOX_CONFIGURATION: android.emu.release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: 17
      
      - name: Generate android folder
        run: yarn expo prebuild --platform android

      - name: Detox rebuild framework cache
        run: yarn detox rebuild-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/app/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Patch build
        run: |
          # https://wix.github.io/Detox/docs/troubleshooting/running-tests/#if-you-do-see-your-app-running-on-the-device
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          # https://github.com/facebook/react-native/issues/36207#issuecomment-1435838521
          sed -i '' 's/android {/android { testBuildType "release"/' android/app/build.gradle

      - name: Detox build
        run: yarn run androidReleaseBuild

      - name: Get device name
        id: device
        run: node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      - name: Run Detox Test(s)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          profile: pixel
          script: yarn run androidReleaseE2E

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts