name: E2E (iOS)

on:
  push:
    branches:
      - '02-26-DetoxTests'

jobs:
  build:
    name: E2E (iOS)
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Install macOS Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
            HOMEBREW_NO_AUTO_UPDATE: 1
            HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Cache CocoaPods
        uses: actions/cache@v3
        id: cache-cocoapods
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: cd ios ; pod install ; cd -

      - name: Detox rebuild framework cache
        run: yarn detox rebuild-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Generate ios folder
        run: yarn expo prebuild --platform ios

      - name: Run Detox Build
        run: yarn run iosReleaseBuild

      - name: Run Detox Test(s)
        run: yarn run iosReleaseE2E
