name: E2E (Android)

on:
  push:
    branches:
      - '02-26-DetoxTests'

jobs:
  build:
    name: E2E (Android)
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Generate android folder
        run: yarn expo prebuild --platform android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 'openjdk8'
          architecture: 'x64'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Detox build
        run: yarn run androidReleaseBuild

      - name: Run Detox Test(s)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_3a_API_33_x86_64
          script: |
            yarn react-native start &
            METRO_BUNDLER_PID=$!
            yarn run androidReleaseE2E
            DETOX_EXIT_CODE=$?
            kill $METRO_BUNDLER_PID
            exit $DETOX_EXIT_CODE

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts